import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";

export const TESTNET_WALRUS_PACKAGE_CONFIG = {
	systemObjectId: "0x6c2547cbbc38025cf3adac45f63cb0a8d12ecf777cdc75a4971612bf97fdf6af",
	stakingPoolId: "0xbe46180321c30aab2f8b3501e24048377287fa708018a5b7c2792b35fe339ee3",
	subsidiesObjectId: "0xda799d85db0429765c8291c594d334349ef5bc09220e79ad397b30106161a0af",
	exchangeIds: [
		"0xf4d164ea2def5fe07dc573992a029e010dba09b1a8dcbc44c5c2e79567f39073",
		"0x19825121c52080bb1073662231cfea5c0e4d905fd13e95f21e9a018f2ef41862",
		"0x83b454e524c71f30803f4d6c302a86fb6a39e96cdfb873c2d1e93bc1c26a3bc5",
		"0x8d63209cf8589ce7aef8f262437163c67577ed09f3e636a9d8e0813843fb8bf1",
	],
}

export const TESTNET_KEYPAIR = Ed25519Keypair.fromSecretKey(
  "suiprivkey1qzmcxscyglnl9hnq82crqsuns0q33frkseks5jw0fye3tuh83l7e6ajfhxx",
);

export const MIST_PER_USDC = 1_000_000;
export const ED25519_SIGNATURE_LENGTH = 64;
export const TESTNET_PACKAGE_ID = "0xe50ff13e71910b2ff376d3a104703b23126da90f8f3dd5539c22e5525aa31241";
export const TESTNET_SUITHETIC_OBJECT = "0x2bfd77629a86a150e208483f44e81f92b97fae3807c1e41f1acb8164bb6b9d39";
export const TESTNET_USDC_TYPE = "0xa1ec7fc00a6f40db9693ad1415d0c193ad3906494428cf252621037bd7117e29::usdc::USDC";
export const TESTNET_DEBUG_OBJECTS = [
	"0xb0efd10b8048742ef792865bde154471e1adb4dac08fc0438808f0f09e6df296",
	"0x449cb6df4298f2864e73d46ff617a6ff1644fdee9ab6fe06e1873deccfc62705",
];

export const TESTNET_AGGREGATORS = ["https://agg.test.walrus.eosusa.io", "https://aggregator.testnet.walrus.atalma.io", "https://aggregator.testnet.walrus.mirai.cloud", "https://aggregator.walrus-01.tududes.com", "https://aggregator.walrus-testnet.walrus.space", "https://aggregator.walrus.banansen.dev", "https://aggregator.walrus.testnet.mozcomputing.dev", "https://sm1-walrus-testnet-aggregator.stakesquid.com", "https://sui-walrus-tn-aggregator.bwarelabs.com", "https://suiftly-testnet-agg.mhax.io", "https://testnet-aggregator-walrus.kiliglab.io", "https://testnet-aggregator.walrus.graphyte.dev", "https://testnet-walrus.globalstake.io", "https://testnet.aggregator.walrus.silentvalidator.com", "https://wal-aggregator-testnet.staketab.org", "https://walrus-agg-test.bucketprotocol.io", "https://walrus-agg-testnet.chainode.tech:9002", "https://walrus-agg.testnet.obelisk.sh", "https://walrus-aggregator-testnet.cetus.zone", "https://walrus-aggregator-testnet.haedal.xyz", "https://walrus-aggregator-testnet.n1stake.com", "https://walrus-aggregator-testnet.staking4all.org", "https://walrus-aggregator-testnet.suisec.tech", "https://walrus-aggregator.thcloud.dev", "https://walrus-test-aggregator.thepassivetrust.com", "https://walrus-testnet-aggregator-1.zkv.xyz", "https://walrus-testnet-aggregator.brightlystake.com", "https://walrus-testnet-aggregator.chainbase.online", "https://walrus-testnet-aggregator.chainflow.io", "https://walrus-testnet-aggregator.crouton.digital", "https://walrus-testnet-aggregator.dzdaic.com", "https://walrus-testnet-aggregator.everstake.one", "https://walrus-testnet-aggregator.luckyresearch.org", "https://walrus-testnet-aggregator.natsai.xyz", "https://walrus-testnet-aggregator.nodeinfra.com", "https://walrus-testnet-aggregator.nodes.guru", "https://walrus-testnet-aggregator.redundex.com", "https://walrus-testnet-aggregator.rpc101.org", "https://walrus-testnet-aggregator.rubynodes.io", "https://walrus-testnet-aggregator.stakecraft.com", "https://walrus-testnet-aggregator.stakeengine.co.uk", "https://walrus-testnet-aggregator.stakely.io", "https://walrus-testnet-aggregator.stakeme.pro", "https://walrus-testnet-aggregator.stakin-nodes.com", "https://walrus-testnet-aggregator.stakingdefenseleague.com.", "https://walrus-testnet-aggregator.starduststaking.com", "https://walrus-testnet-aggregator.talentum.id", "https://walrus-testnet-aggregator.trusted-point.com", "https://walrus-testnet.blockscope.net", "https://walrus-testnet.lionscraft.blockscape.network:9000", "https://walrus-testnet.validators.services.kyve.network/aggregate", "https://walrus-testnet.veera.com", "https://walrus-tn.juicystake.io:9443", "https://walrus.testnet.aggregator.stakepool.dev.br", "https://walrusagg.testnet.pops.one", "http://cs74th801mmedkqu25ng.bdnodes.net:8443", "http://walrus-storage.testnet.nelrann.org:9000", "http://walrus-testnet.equinoxdao.xyz:9000", "http://walrus-testnet.suicore.com:9000"];

export const TESTNET_PUBLISHERS = ["https://publisher.testnet.walrus.atalma.io", "https://publisher.walrus-01.tududes.com", "https://publisher.walrus-testnet.walrus.space", "https://publisher.walrus.banansen.dev", "https://sm1-walrus-testnet-publisher.stakesquid.com", "https://sui-walrus-testnet-publisher.bwarelabs.com", "https://suiftly-testnet-pub.mhax.io", "https://testnet-publisher-walrus.kiliglab.io", "https://testnet-publisher.walrus.graphyte.dev", "https://testnet.publisher.walrus.silentvalidator.com", "https://wal-publisher-testnet.staketab.org", "https://walrus-publish-testnet.chainode.tech:9003", "https://walrus-publisher-testnet.n1stake.com", "https://walrus-publisher-testnet.staking4all.org", "https://walrus-publisher.rubynodes.io", "https://walrus-publisher.thcloud.dev", "https://walrus-testnet-published.luckyresearch.org", "https://walrus-testnet-publisher-1.zkv.xyz", "https://walrus-testnet-publisher.crouton.digital", "https://walrus-testnet-publisher.dzdaic.com", "https://walrus-testnet-publisher.everstake.one", "https://walrus-testnet-publisher.nami.cloud", "https://walrus-testnet-publisher.natsai.xyz", "https://walrus-testnet-publisher.nodeinfra.com", "https://walrus-testnet-publisher.nodes.guru", "https://walrus-testnet-publisher.redundex.com", "https://walrus-testnet-publisher.rpc101.org", "https://walrus-testnet-publisher.stakecraft.com", "https://walrus-testnet-publisher.stakeengine.co.uk", "https://walrus-testnet-publisher.stakely.io", "https://walrus-testnet-publisher.stakeme.pro", "https://walrus-testnet-publisher.stakingdefenseleague.com.", "https://walrus-testnet-publisher.starduststaking.com", "https://walrus-testnet-publisher.trusted-point.com", "https://walrus-testnet.blockscope.net:11444", "https://walrus-testnet.validators.services.kyve.network/publish", "https://walrus.testnet.publisher.stakepool.dev.br", "http://walrus-publisher-testnet.cetus.zone:9001", "http://walrus-publisher-testnet.haedal.xyz:9001", "http://walrus-publisher-testnet.suisec.tech:9001", "http://walrus-storage.testnet.nelrann.org:9001", "http://walrus-testnet.equinoxdao.xyz:9001", "http://walrus-testnet.suicore.com:9001", "http://walrus.testnet.pops.one:9001", "http://waltest.chainflow.io:9001"];
